// Generated by gencpp from file interaction/position_msg.msg
// DO NOT EDIT!


#ifndef INTERACTION_MESSAGE_POSITION_MSG_H
#define INTERACTION_MESSAGE_POSITION_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace interaction
{
template <class ContainerAllocator>
struct position_msg_
{
  typedef position_msg_<ContainerAllocator> Type;

  position_msg_()
    : x(0)
    , y(0)
    , z(0)  {
    }
  position_msg_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;

   typedef uint32_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::interaction::position_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::interaction::position_msg_<ContainerAllocator> const> ConstPtr;

}; // struct position_msg_

typedef ::interaction::position_msg_<std::allocator<void> > position_msg;

typedef boost::shared_ptr< ::interaction::position_msg > position_msgPtr;
typedef boost::shared_ptr< ::interaction::position_msg const> position_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::interaction::position_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::interaction::position_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::interaction::position_msg_<ContainerAllocator1> & lhs, const ::interaction::position_msg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::interaction::position_msg_<ContainerAllocator1> & lhs, const ::interaction::position_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace interaction

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::interaction::position_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::interaction::position_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaction::position_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::interaction::position_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaction::position_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::interaction::position_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::interaction::position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bfde2953ee46d97d36a711ef3cbc85f4";
  }

  static const char* value(const ::interaction::position_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbfde2953ee46d97dULL;
  static const uint64_t static_value2 = 0x36a711ef3cbc85f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::interaction::position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "interaction/position_msg";
  }

  static const char* value(const ::interaction::position_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::interaction::position_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n"
"uint32 y\n"
"uint32 z\n"
;
  }

  static const char* value(const ::interaction::position_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::interaction::position_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::interaction::position_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::interaction::position_msg_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTERACTION_MESSAGE_POSITION_MSG_H
