// Generated by gencpp from file interaction/product_srv.msg
// DO NOT EDIT!


#ifndef INTERACTION_MESSAGE_PRODUCT_SRV_H
#define INTERACTION_MESSAGE_PRODUCT_SRV_H

#include <ros/service_traits.h>


#include <interaction/product_srvRequest.h>
#include <interaction/product_srvResponse.h>


namespace interaction
{

struct product_srv
{

typedef product_srvRequest Request;
typedef product_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct product_srv
} // namespace interaction


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interaction::product_srv > {
  static const char* value()
  {
    return "9b383809021b2be879ecb6c4bb797d14";
  }

  static const char* value(const ::interaction::product_srv&) { return value(); }
};

template<>
struct DataType< ::interaction::product_srv > {
  static const char* value()
  {
    return "interaction/product_srv";
  }

  static const char* value(const ::interaction::product_srv&) { return value(); }
};


// service_traits::MD5Sum< ::interaction::product_srvRequest> should match
// service_traits::MD5Sum< ::interaction::product_srv >
template<>
struct MD5Sum< ::interaction::product_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interaction::product_srv >::value();
  }
  static const char* value(const ::interaction::product_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interaction::product_srvRequest> should match
// service_traits::DataType< ::interaction::product_srv >
template<>
struct DataType< ::interaction::product_srvRequest>
{
  static const char* value()
  {
    return DataType< ::interaction::product_srv >::value();
  }
  static const char* value(const ::interaction::product_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interaction::product_srvResponse> should match
// service_traits::MD5Sum< ::interaction::product_srv >
template<>
struct MD5Sum< ::interaction::product_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interaction::product_srv >::value();
  }
  static const char* value(const ::interaction::product_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interaction::product_srvResponse> should match
// service_traits::DataType< ::interaction::product_srv >
template<>
struct DataType< ::interaction::product_srvResponse>
{
  static const char* value()
  {
    return DataType< ::interaction::product_srv >::value();
  }
  static const char* value(const ::interaction::product_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERACTION_MESSAGE_PRODUCT_SRV_H
