const char ERROR_PAGE[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<title>Online alarm</title>\n"
"<meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
"    body {\n"
"        font-family: Courier, monospace;\n"
"        margin: 0;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    \n"
"    header {\n"
"        font-family: Courier, monospace;\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        font-size: 28px;\n"
"        color: black;\n"
"        overflow: hidden;\n"
"    }\n"
"    \n"
"    footer {\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        position: fixed;\n"
"        left: 0;\n"
"        bottom: 0;\n"
"        width: 100%;\n"
"        height: 10%;\n"
"        padding-top: 5%;\n"
"        opacity: 0.5;\n"
"    }\n"
"    \n"
"    a {\n"
"        text-decoration: none;\n"
"        color: black;\n"
"    }\n"
"</style>\n"
"\n"
"<body>\n"
"\n"
"    <header>\n"
"        <a href=\"/\">\n"
"            <h2>ALARMA ONLINE</h2>\n"
"        </a>\n"
"    </header>\n"
"\n"
"    <h2 style=\"text-align: center;\">Error 404 Not Found</h2>\n"
"\n"
"    <footer>\n"
"        Powered by Vistor© 2020. All Rights Reserved\n"
"    </footer>\n"
"</body>\n"
"\n"
"</html>";

const char MAIN_PAGE[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"<title>Online alarm</title>\n"
"<meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
"    body {\n"
"        font-family: Courier, monospace;\n"
"        margin: 0;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    \n"
"    header {\n"
"        font-family: Courier, monospace;\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        font-size: 28px;\n"
"        color: black;\n"
"        overflow: hidden;\n"
"    }\n"
"    \n"
"    footer {\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        position: fixed;\n"
"        left: 0;\n"
"        bottom: 0;\n"
"        width: 100%;\n"
"        height: 10%;\n"
"        padding-top: 5%;\n"
"        opacity: 0.5;\n"
"    }\n"
"    \n"
"    p {\n"
"        padding: 5%;\n"
"    }\n"
"    \n"
"    .w-5 {\n"
"        width: 5%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-10 {\n"
"        width: 10%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-15 {\n"
"        width: 15%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-20 {\n"
"        width: 20%;\n"
"        text-align: center;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-25 {\n"
"        width: 25%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-30 {\n"
"        width: 30%;\n"
"        text-align: center;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-35 {\n"
"        width: 35%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-40 {\n"
"        width: 40%;\n"
"        text-align: center;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-45 {\n"
"        width: 45%;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-50 {\n"
"        width: 50%;\n"
"        text-align: center;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .w-third {\n"
"        width: 33.33333%;\n"
"        text-align: center;\n"
"        float: left;\n"
"    }\n"
"    \n"
"    .fill,\n"
"    .value-button {\n"
"        display: inline-block;\n"
"        margin: 0px;\n"
"        width: 100%;\n"
"        height: 20px;\n"
"        font-size: 20px;\n"
"        text-align: center;\n"
"        padding: 11px 0;\n"
"        background: rgb(250, 250, 250);\n"
"        -webkit-touch-callout: none;\n"
"        -webkit-user-select: none;\n"
"        -khtml-user-select: none;\n"
"        -moz-user-select: none;\n"
"        -ms-user-select: none;\n"
"        user-select: none;\n"
"    }\n"
"    \n"
"    .value-button:hover {\n"
"        cursor: pointer;\n"
"        background: rgb(236, 236, 236);\n"
"    }\n"
"    \n"
"    form #decrease-left {\n"
"        border-radius: 0 0 0 8px;\n"
"    }\n"
"    \n"
"    form #increase-left {\n"
"        border-radius: 8px 0 0 0;\n"
"    }\n"
"    \n"
"    form #decrease-right {\n"
"        border-radius: 0 0 8px 0;\n"
"    }\n"
"    \n"
"    form #increase-right {\n"
"        border-radius: 0 8px 0 0;\n"
"    }\n"
"    \n"
"    form #input-wrap {\n"
"        margin: 0px;\n"
"        padding: 0px;\n"
"    }\n"
"    \n"
"    .colon {\n"
"        text-align: center;\n"
"        font-size: 32px;\n"
"        border: none;\n"
"        margin: 0.8px;\n"
"        padding: 2%;\n"
"        width: 100%;\n"
"        height: 40px;\n"
"    }\n"
"    \n"
"    input#minute,\n"
"    input#hour {\n"
"        text-align: center;\n"
"        font-size: 32px;\n"
"        border: none;\n"
"        margin: 0px;\n"
"        padding: 2%;\n"
"        width: 100%;\n"
"        height: 40px;\n"
"    }\n"
"    \n"
"    input[type=number]::-webkit-inner-spin-button,\n"
"    input[type=number]::-webkit-outer-spin-button {\n"
"        -webkit-appearance: none;\n"
"        margin: 0;\n"
"    }\n"
"    \n"
"    input[type=submit] {\n"
"        width: 50%;\n"
"        background-color: #4CAF50;\n"
"        color: white;\n"
"        padding: 14px 20px;\n"
"        margin: 32px 0;\n"
"        border: none;\n"
"        border-radius: 4px;\n"
"        cursor: pointer;\n"
"    }\n"
"    \n"
"    input[type=submit]:hover {\n"
"        background-color: #45a049;\n"
"    }\n"
"</style>\n"
"\n"
"<body>\n"
"\n"
"    <header>\n"
"        <h2>ALARMA ONLINE</h2>\n"
"    </header>\n"
"\n"
"    <div>\n"
"        <div class=\"w-third\">\n"
"            <p></p>\n"
"        </div>\n"
"        <div class=\"w-third\">\n"
"            <h2>Introducir hora</h2>\n"
"            <form action=\"/set\" method=\"GET\">\n"
"                <div class=\"w-45\">\n"
"                    <div class=\"value-button\" id=\"increase-left\" onclick=\"increaseValue()\" value=\"Increase Value\">&#8593</div><br>\n"
"                    <input type=\"number\" id=\"hour\" name=\"hour\" value=\"7\" /><br>\n"
"                    <div class=\"value-button\" id=\"decrease-left\" onclick=\"decreaseValue()\" value=\"Decrease Value\">&#8595</div>\n"
"                </div>\n"
"                <div class=\"w-10\">\n"
"                    <div class=\"fill\"></div><br>\n"
"                    <div class=\"colon\">:</div>\n"
"                    <div class=\"fill\"></div><br>\n"
"                </div>\n"
"                <div class=\"w-45\">\n"
"                    <div class=\"value-button\" id=\"increase-right\" onclick=\"increaseMinuteValue()\" value=\"Increase Value\">&#8593</div><br>\n"
"                    <input type=\"number\" id=\"minute\" name=\"minute\" value=\"30\" /><br>\n"
"                    <div class=\"value-button\" id=\"decrease-right\" onclick=\"decreaseMinuteValue()\" value=\"Decrease Value\">&#8595</div><br>\n"
"                </div>\n"
"                <input type=\"submit\" value=\"Set\">\n"
"            </form>\n"
"        </div>\n"
"        <div class=\"w-third\">\n"
"            <p><span id=\"datetime\"></span></p>\n"
"        </div>\n"
"    </div>\n"
"\n"
"    <footer>\n"
"        Powered by Vistor© 2020. All Rights Reserved\n"
"    </footer>\n"
"\n"
"    <script>\n"
"        var myVar = setInterval(myTimer, 100);\n"
"\n"
"        function myTimer() {\n"
"            var d = new Date();\n"
"            var t = d.toLocaleTimeString();\n"
"            document.getElementById(\"datetime\").innerHTML = t;\n"
"        }\n"
"\n"
"        function increaseValue() {\n"
"            var value = parseInt(document.getElementById('hour').value, 10);\n"
"            value = isNaN(value) ? 0 : value;\n"
"            value > 22 ? value = -1 : '';\n"
"            value++;\n"
"            document.getElementById('hour').value = value;\n"
"        }\n"
"\n"
"        function decreaseValue() {\n"
"            var value = parseInt(document.getElementById('hour').value, 10);\n"
"            value = isNaN(value) ? 0 : value;\n"
"            value < 1 ? value = 24 : '';\n"
"            value--;\n"
"            document.getElementById('hour').value = value;\n"
"        }\n"
"\n"
"        function increaseMinuteValue() {\n"
"            var value = parseInt(document.getElementById('minute').value, 10);\n"
"            value = isNaN(value) ? 0 : value;\n"
"            value > 58 ? value = -1 : '';\n"
"            value++;\n"
"            document.getElementById('minute').value = value;\n"
"        }\n"
"\n"
"        function decreaseMinuteValue() {\n"
"            var value = parseInt(document.getElementById('minute').value, 10);\n"
"            value = isNaN(value) ? 0 : value;\n"
"            value < 1 ? value = 60 : '';\n"
"            value--;\n"
"            document.getElementById('minute').value = value;\n"
"        }\n"
"    </script>\n"
"</body>\n"
"\n"
"</html>";

const char SET_PAGE[] = 
"<!DOCTYPE html>\n"
"<html>\n"
"<title>Online alarm</title>\n"
"<meta charset=\"UTF-8\" name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<style>\n"
"    body {\n"
"        font-family: Courier, monospace;\n"
"        margin: 0;\n"
"        background-color: #ffffff;\n"
"    }\n"
"    \n"
"    header {\n"
"        font-family: Courier, monospace;\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        font-size: 28px;\n"
"        color: black;\n"
"        overflow: hidden;\n"
"    }\n"
"    \n"
"    footer {\n"
"        background-color: rgb(245, 245, 245);\n"
"        text-align: center;\n"
"        position: fixed;\n"
"        left: 0;\n"
"        bottom: 0;\n"
"        width: 100%;\n"
"        height: 10%;\n"
"        padding-top: 5%;\n"
"        opacity: 0.5;\n"
"    }\n"
"    \n"
"    a {\n"
"        text-decoration: none;\n"
"        color: black;\n"
"    }\n"
"    \n"
"    .padding-5 {\n"
"        padding: 5%;\n"
"    }\n"
"</style>\n"
"\n"
"<body>\n"
"\n"
"    <header>\n"
"        <a href=\"/\">\n"
"            <h2>ALARMA ONLINE</h2>\n"
"        </a>\n"
"    </header>\n"
"\n"
"    <h2 class=\"padding-5\">Alarma configurada para las <span id=\"hour\"></span> y <span id=\"minute\"></span>.</h2>\n"
"\n"
"    <footer>\n"
"        Powered by Vistor© 2020. All Rights Reserved\n"
"    </footer>\n"
"\n"
"    <script>\n"
"        var myVar = setInterval(myTimer, 100);\n"
"\n"
"        function myTimer() {\n"
"            var d = new Date();\n"
"            var t = d.toLocaleTimeString();\n"
"            document.getElementById(\"datetime\").innerHTML = t;\n"
"        }\n"
"\n"
"        const params = new URLSearchParams(document.location.search);\n"
"        var hour = params.get(\"hour\");\n"
"        var minute = params.get(\"minute\");\n"
"        document.getElementById(\"hour\").innerHTML = hour;\n"
"        document.getElementById(\"minute\").innerHTML = minute;\n"
"    </script>\n"
"</body>\n"
"\n"
"</html>";

//const char TEST_PAGE[] =
//;
